### ISSUE TITLE
dicom data does not have pixel_array ?

### ISSUE THREAD

**Issue by hexiao0275** [matteo-bastico/MI-Seg#1]
dicom data does not have pixel_array?
![QQ截图20231026054513](https://github.com/matteo-bastico/MI-Seg/assets/68224838/f68c43f6-a97e-4600-a7b9-7c3dd7c9c91f)

**Comment by matteo-bastico** [comment]
Hello @hexiao-cs, could you detail more the issue? Did you try to preprocess the data with the notebook load_data.ipynb?

**Comment by matteo-bastico** [comment]
Closing the issue. Feel free to re-open it if needed.
