### ISSUE TITLE
Pre trained models are not found in the provided link. 

### ISSUE THREAD

**Issue by naveen27b** [matteo-bastico/MI-Seg#3]
Hi, thank you for the amazing work. But I cant find the pretrained models and weights in the provided link. Can you please provide them? 
![image](https://github.com/matteo-bastico/MI-Seg/assets/22679181/67356fb1-06bf-463c-a400-752cd73a01f5)

**Comment by matteo-bastico** [comment]
Hello, the link has be updated in the README. 

You can download the weights at [this drive](https://drive.google.com/drive/folders/1S-GdryfNziYV4088jh4meVbqdWkdEwuL?usp=sharing).
